name: Latest

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  latest:
    name: Update `latest` branch

    if: github.even.repository.fork == false

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: latest

      - name: Pull from tag
        run: |
          git fetch origin
          git merge $GITHUB_REF --ff-only -m 'Update to latest tag'
          git push origin latest
