name: Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    name: Typecheck Code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: compile-mode.nvim

      - name: Setup `plenary.nvim`
        uses: actions/checkout@v4
        with:
          repository: nvim-lua/plenary.nvim
          path: "${{ github.workspace }}/plenary.nvim"

      - name: Setup Neovim Runtime
        uses: actions/checkout@v4
        with:
          repository: neovim/neovim
          path: "${{ github.workspace }}/neovim"

      - name: Typecheck
        uses: mrcjkb/lua-typecheck-action@v1
        env:
          VIMRUNTIME: "${{ github.workspace }}/neovim/runtime"
          PLENARY_PATH: "${{ github.workspace }}/plenary.nvim"
        with:
          directories: |
            compile-mode.nvim
          configpath: compile-mode.nvim/.luarc-ci.json
